vich_uploader:
    db_driver: orm

    mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
        attachments:
            uri_prefix: /images/samples
            upload_destination: '%kernel.project_dir%/public/images/samples'
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'stone.id' }
